// <auto-generated />
using Fernanda.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fernanda.Migrations
{
    [DbContext(typeof(AppDataContext))]
    partial class AppDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.20");

            modelBuilder.Entity("Fernanda.Models.Consumo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("adicinionalBandeira")
                        .HasColumnType("REAL");

                    b.Property<int>("ano")
                        .HasColumnType("INTEGER");

                    b.Property<string>("bandeira")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("consumoFaturado")
                        .HasColumnType("REAL");

                    b.Property<double>("m3Consumidos")
                        .HasColumnType("REAL");

                    b.Property<int>("mes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("possuiEsgoto")
                        .HasColumnType("INTEGER");

                    b.Property<double>("tarifa")
                        .HasColumnType("REAL");

                    b.Property<double>("taxaEsgoto")
                        .HasColumnType("REAL");

                    b.Property<double>("total")
                        .HasColumnType("REAL");

                    b.Property<double>("valorAgua")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Consumos");
                });
#pragma warning restore 612, 618
        }
    }
}
